name: Semantic release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    environment: deploy-env

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Semantic Release
        run: |
          echo "Update version package..."
          semantic-release version
          echo "update version" 
